### ISSUE TITLE
elsif block in line 390 is never executed

### ISSUE THREAD

**Issue by jtrees** [gkovacs/pdfocr#37]
Here is the code:

```
if usetesseract
        puts "renaming merged-new.pdf to merged.pdf"
        sh "mv #{tmp+'/0000000000000-merged-new.pdf'} #{tmp+'/merged.pdf'}"
elsif
        puts "Merging together PDF files"
        sh "pdftk #{tmp+'/'+'*-new.pdf'} cat output #{tmp+'/merged.pdf'}"
end
```

Is there a condition missing here or should the `elsif` be an `else`?

In any case the condition being evaluated is actually the return value of `puts` which is always `nil` so the block will never be executed.

**Comment by gkovacs** [comment]
yes that should be a else
